# This is a basic workflow to help you get started with Actions

name: build-reen-rootfs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-reen-rootfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: debug-dir
        run: pwd

      - name: debug-content
        run: ls -lah

      - name: docker build
        run: docker build $GITHUB_WORKSPACE --tag rootfs-image

      - name: run & export
        run: docker run -d --name reen-rootfs rootfs-image && docker export reen-rootfs > reen_rootfs.tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: reen-rootfs-artifact
          path: $GITHUB_WORKSPACE/reen_rootfs.tar.gz